In [27]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv('C:\\Users\\aanya\\Downloads\\train.csv\\train.csv')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     550068 non-null  int64  
 1   Product_ID                  550068 non-null  object 
 2   Gender                      550068 non-null  object 
 3   Age                         550068 non-null  object 
 4   Occupation                  550068 non-null  int64  
 5   City_Category               550068 non-null  object 
 6   Stay_In_Current_City_Years  550068 non-null  object 
 7   Marital_Status              550068 non-null  int64  
 8   Product_Category_1          550068 non-null  int64  
 9   Product_Category_2          376430 non-null  float64
 10  Product_Category_3          166821 non-null  float64
 11  Purchase                    550068 non-null  int64  
dtypes: float64(2), int64(5), object(5)
memory usage: 50.4+ MB


In [8]:
df

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
...         ...        ...    ...    ...         ...           ...   
550063  1006033  P00372445      M  51-55          13             B   
550064  1006035  P00375436      F  26-35           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550066  1006038  P00375436      F    55+           1             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               0                   3   
1                               2               0                   1   
2                               2               0                  12   
3                               2               0                  12   
4                              4+               0                   8   
...                           ...             ...                 ...   
550063                          1               1                  20   
550064                          3               0                  20   
550065                         4+               1                  20   
550066                          2               0                  20   
550067                         4+               1                  20   

        Product_Category_2  Product_Category_3  Purchase  
0                      NaN                 NaN      8370  
1                      6.0                14.0     15200  
2                      NaN                 NaN      1422  
3                     14.0                 NaN      1057  
4                      NaN                 NaN      7969  
...                    ...                 ...       ...  
550063                 NaN                 NaN       368  
550064                 NaN                 NaN       371  
550065                 NaN                 NaN       137  
550066                 NaN                 NaN       365  
550067                 NaN                 NaN       490  

[550068 rows x 12 columns]

In [9]:
df.isnull().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [10]:
df.dropna()

User_ID Product_ID Gender    Age  Occupation City_Category  \
1       1000001  P00248942      F   0-17          10             A   
6       1000004  P00184942      M  46-50           7             B   
13      1000005  P00145042      M  26-35          20             A   
14      1000006  P00231342      F  51-55           9             A   
16      1000006   P0096642      F  51-55           9             A   
...         ...        ...    ...    ...         ...           ...   
545902  1006039  P00064042      F  46-50           0             B   
545904  1006040  P00081142      M  26-35           6             B   
545907  1006040  P00277642      M  26-35           6             B   
545908  1006040  P00127642      M  26-35           6             B   
545914  1006040  P00217442      M  26-35           6             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
1                               2               0                   1   
6                               2               1                   1   
13                              1               1                   1   
14                              1               0                   5   
16                              1               0                   2   
...                           ...             ...                 ...   
545902                         4+               1                   3   
545904                          2               0                   6   
545907                          2               0                   2   
545908                          2               0                   1   
545914                          2               0                   1   

        Product_Category_2  Product_Category_3  Purchase  
1                      6.0                14.0     15200  
6                      8.0                17.0     19215  
13                     2.0                 5.0     15665  
14                     8.0                14.0      5378  
16                     3.0                 4.0     13055  
...                    ...                 ...       ...  
545902                 4.0                12.0      8047  
545904                 8.0                14.0     16493  
545907                 3.0                10.0      3425  
545908                 2.0                15.0     15694  
545914                 2.0                11.0     11640  

[166821 rows x 12 columns]

In [16]:
del df['Product_Category_2']
del df['Product_Category_3']

In [17]:
df

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
...         ...        ...    ...    ...         ...           ...   
550063  1006033  P00372445      M  51-55          13             B   
550064  1006035  P00375436      F  26-35           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550066  1006038  P00375436      F    55+           1             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               0                   3   
1                               2               0                   1   
2                               2               0                  12   
3                               2               0                  12   
4                              4+               0                   8   
...                           ...             ...                 ...   
550063                          1               1                  20   
550064                          3               0                  20   
550065                         4+               1                  20   
550066                          2               0                  20   
550067                         4+               1                  20   

        Purchase  
0           8370  
1          15200  
2           1422  
3           1057  
4           7969  
...          ...  
550063       368  
550064       371  
550065       137  
550066       365  
550067       490  

[550068 rows x 10 columns]

In [18]:
df.User_ID.nunique()

5891

In [19]:
df.Product_ID.nunique()

3631

In [20]:
df.Gender.unique()

array(['F', 'M'], dtype=object)

In [21]:
df.Age.unique()

array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25'],
      dtype=object)

In [22]:
df.Occupation.unique()

array([10, 16, 15,  7, 20,  9,  1, 12, 17,  0,  3,  4, 11,  8, 19,  2, 18,
        5, 14, 13,  6], dtype=int64)

In [23]:
df.City_Category.unique()

array(['A', 'C', 'B'], dtype=object)

In [24]:
df.Stay_In_Current_City_Years.unique()

array(['2', '4+', '3', '1', '0'], dtype=object)

In [25]:
df.Marital_Status.unique()

array([0, 1], dtype=int64)

In [26]:
df.Product_Category_1.unique()

array([ 3,  1, 12,  8,  5,  4,  2,  6, 14, 11, 13, 15,  7, 16, 18, 10, 17,
        9, 20, 19], dtype=int64)

In [28]:
df.Purchase.mean()

9263.968712959126

In [33]:
for column in df.columns:
    print(column, ":" ,df[column].nunique())

User_ID : 5891
Product_ID : 3631
Gender : 2
Age : 7
Occupation : 21
City_Category : 3
Stay_In_Current_City_Years : 5
Marital_Status : 2
Product_Category_1 : 20
Purchase : 18105
